---
title: "Ernesto"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r cars}
if(!require(readr)) {install.packages("readr")}
library("readr")
if(!require(dplyr)) {install.packages('dplyr')}
library("dplyr")
if(!require(ggplot2)) {install.packages('ggplot2')}
library("ggplot2")
if(!require(tidyverse)) {install.packages('tidyverse')}
library("tidyverse")
if(!require(ggthemes)) {install.packages('ggthemes')}
library("ggthemes")
if(!require(ggthemes)) {install.packages('lubridate')}
library("lubridate")
#==Pregunta 1====================================================
cyberb <- read_csv("Cyber Security Breaches.csv")

cyberb$Type_of_Breach <- as.factor(cyberb$Type_of_Breach)
cyberb$Date_Posted_or_Updated <- as.Date(cyberb$Date_Posted_or_Updated,format="%d/%m/%Y")
cyberb$breach_start <- as.Date(cyberb$breach_start,format="%d/%m/%Y")
cyberb$breach_end <- as.Date(cyberb$breach_end,format="%d/%m/%Y")


cb2 <- data.frame(Type_of_Breach= cyberb$Type_of_Breach,Individuals_Affected = cyberb$Individuals_Affected)

by_type <- cb2 %>% group_by(Type_of_Breach)

by_type_sum <- by_type %>% summarise(Individuals_Affected = sum(Individuals_Affected))

by_type_top5 <-  by_type_sum %>%
                  arrange(desc(Individuals_Affected))%>%
                  slice(1:5)

ggplot(data = by_type_top5,
       mapping = aes(Type_of_Breach, Individuals_Affected))+
  geom_col()+
  xlab("Tipos de brechas")+
  ylab("Cantidad")+
  ggtitle(("El top 5 de tipos de brechas"))+
  theme_stata()

#==Pregunta 2=========================================================
mean((cyberb$breach_end - cyberb$breach_start), na.rm = T)

#===Pregunta 3==============================================================

cyberb$Location_of_Breached_Information <- as.factor(cyberb$Location_of_Breached_Information)

dfc2 <- cyberb %>%
    group_by(Location_of_Breached_Information) %>%
    summarise(count = n()) %>%
    top_n(n = 5, wt = count)

ggplot(data = dfc2,
       mapping = aes(x = Location_of_Breached_Information,y = count))+
  geom_col()+
  xlab("Medio de almacenamiento de información")+
  ylab("Cantidad")+
  ggtitle(("El top 5 de tipos de brechas"))+
  theme_stata()

#===Pregunta 4============================================================
cyberb$State <- as.factor(cyberb$State)

dfc3 <- cyberb %>%
    group_by(State) %>%
    summarise(count = n()) %>%
    top_n(n = 5, wt = count)

ggplot(data = dfc3,
       mapping = aes(x = State,y = count))+
  geom_col()+
  xlab("Medio de almacenamiento de información")+
  ylab("Cantidad")+
  ggtitle(("El top 5 de estados atacados"))+
  theme_stata()
#===Pregunta 5=========================================================
sum(!is.na(cyberb$Business_Associate_Involved))

```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
